# Generated by Django 2.2.1 on 2019-05-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1000)),
                ('social_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='social_django.UserSocialAuth')),
            ],
            options={
                'verbose_name_plural': 'Access Tokens',
            },
        ),
    ]
